### ISSUE TITLE
Set up branding page for PyMCon

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/brand#16]
Examples:   
1. scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/main/doc/logos/README.md
2. PyMC: https://github.com/pymc-devs/brand/blob/main/README.md

**Comment by reshamas** [comment]
[@rowangayleschaefer](https://github.com/rowangayleschaefer) may be able to take this issue.

**Comment by OriolAbril** [comment]
Related to https://github.com/pymc-devs/brand/pull/14#issuecomment-1304824346. I think it is ok to start with a very short summary, things like: when would one use the horizontal logo instead of the official one? should we choose the one that looks better or try to avoid the horizontal one if possible? what about the text only logo? I am not sure a 1 by 1 in depth description of each logo would be worth it

**Comment by reshamas** [comment]
@rowangayleschaefer THANKS for getting this started!!!  

Some tweaks that we need to make:  
1) Can we move the "[pymcon-logos](https://github.com/pymc-devs/brand/tree/main/pymcon-logos)" folder under "pymcon"
2) The white on white background logos aren't viewable (logo 5).  Is there a better way to present them?

cc:  @canyon289 @cuchoi

**Comment by reshamas** [comment]
Closed via #18
